# This example is based on the Google Kubernetes Engine
# StorageClass named "standard"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # The name "standard-xfs" is used in the YAML files
  name: standard-xfs
parameters:
  # You must add this parameter to force an XFS file system
  fsType: xfs
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
