# This example is based on the Google Cloud Platform (GCP)
# Google Kubernetes Engine (GKE) StorageClass named "standard"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # The name "sg-xfs" is used in the YAML files
  name: sg-xfs
parameters:
  # You must add this parameter to force an XFS file system
  fsType: xfs
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
