# Copyright (c) 2019-2020 NetApp, Inc., All Rights Reserved
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb0-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb1-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb2-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb0-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb1-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb2-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb0-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb1-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb2-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # Customized storageClass with XFS file system
  storageClassName: sg-xfs
---
kind: Service
apiVersion: v1
metadata:
  name: dc1-storage-node
spec:
  type: LoadBalancer
  selector:
    app: dc1-sn-app
  ports:
  - name: s3-sn-012-https
    port: 18082
    targetPort: 18082
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: dc1-sn
spec:
  serviceName: "pod-dns"
  replicas: 3
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: pod-dns
  template:
    metadata:
      labels:
        app: dc1-sn-app
        name: pod-dns
    spec:
      containers:
      - name: sn-container
        image: storagegrid-11.9.0:Storage_Node
        resources:
          limits:
            memory: 24Gi
          requests:
            cpu: 8
            memory: 24Gi
        securityContext:
          capabilities:
            add:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_TIME
            - SYS_NICE
            - DAC_READ_SEARCH
            - SYS_RESOURCE
            - SYSLOG
            - SYS_PTRACE
        env:
        - name: SG_CONTAINER_TYPE
          value: Kubernetes
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ADMIN_DNS_NAME
          value: "dc1-adm-0.pod-dns"
        volumeMounts:
        - mountPath: "/tmp"
          name: tmp
        - mountPath: "/var/local"
          name: var-local
        - mountPath: "/var/local/rangedb/0"
          name: rangedb0
        - mountPath: "/var/local/rangedb/1"
          name: rangedb1
        - mountPath: "/var/local/rangedb/2"
          name: rangedb2
        - mountPath: "/var/local/nginx/spool"
          name: nginx-spool
      volumes:
      - name: nginx-spool
        emptyDir:
          medium: Memory
          sizeLimit: 64Mi
      - name: tmp
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: var-local
  - metadata:
      name: rangedb0
  - metadata:
      name: rangedb1
  - metadata:
      name: rangedb2
