# This example is based on the Amazon Web Services (AWS)
# Elastic Kubernetes Service (EKS) StorageClass named "gp2"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  # The name "sg-xfs" is used in the YAML files
  name: sg-xfs
parameters:
  fsType: xfs
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
