---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: dc1-arc
spec:
  serviceName: "pod-dns"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: pod-dns
  template:
    metadata:
      labels:
        app: arc-app
        name: pod-dns
    spec:
      containers:
      - name: arc-container
        # The image must be available on each K8s Worker
        # Either make this image avalable on every K8s worker node
        # Or host the images on a private repository and update this entry accordingly
        image: storagegrid-11.1.1:Archive_Node
        resources:
          limits:
            cpu: 8
            memory: 24Gi
        securityContext:
          capabilities:
            add: [NET_ADMIN, SYS_ADMIN, SYS_TIME, NET_BIND_SERVICE, SETGID, SETUID, DAC_READ_SEARCH, SYS_RESOURCE, SYSLOG, SYS_PTRACE]
        env:
        - name: HV_ENV
          value: Kubernetes
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ADMIN_IP
          value: "dc1-adm-0.pod-dns"
        volumeMounts:
        - mountPath: "/var/local"
          name: var-local
        command: ["/usr/bin/initSG.sh"]
  volumeClaimTemplates:
  # These are mapped using the namespace and StatefullSet ID
  - metadata:
      name: var-local
