---
kind: Service
apiVersion: v1
metadata:
  name: gateway-service
spec:
  type: NodePort
  ports:
  - name: s3-gw-https
    port: 8082
    nodePort: 32082
    targetPort: 8082
  selector:
    app: gw-app
