---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-adm-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dc1-adm-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-dc1-adm-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb0-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb1-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb2-dc1-sn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb0-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb1-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb2-dc1-sn-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb0-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb1-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rangedb2-dc1-sn-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  # This line must be updated
  # Use a storageClass from your cloud provider
  storageClassName: tridentbasic
