# Copyright (c) 2019 NetApp, Inc., All Rights Reserved
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-adm-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dc1-adm-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-dc1-adm-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
kind: Service
apiVersion: v1
metadata:
  name: pod-dns
  labels:
    name: pod-dns
spec:
  selector:
    name: pod-dns
  clusterIP: None
  ports:
  # Although unused, headless service definitions require a port to be declared
  - name: unused
    port: 12345
    targetPort: 12345
---
kind: Service
apiVersion: v1
metadata:
  name: dc1-admin-node
spec:
  type: LoadBalancer
  selector:
    app: dc1-adm-app
  ports:
  - name: gmi-http
    port: 80
    targetPort: 80
  - name: gmi-https
    port: 443
    targetPort: 443
  # Optional connectivity for administration
  # - name: gmi-ssh
  #   port: 22
  #   targetPort: 22
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: dc1-adm
spec:
  serviceName: "pod-dns"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: pod-dns
  template:
    metadata:
      labels:
        app: dc1-adm-app
        name: pod-dns
    spec:
      containers:
      - name: adm-container
        image: storagegrid-12.0.0:Admin_Node
        resources:
          limits:
            memory: 24Gi
          requests:
            cpu: 8
            memory: 24Gi
        ports:
        - name: gmi-https
          containerPort: 443
        securityContext:
          capabilities:
            add:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_TIME
            - SYS_NICE
            - DAC_READ_SEARCH
            - SYS_RESOURCE
            - SYSLOG
            - SYS_PTRACE
        env:
        - name: SG_CONTAINER_TYPE
          value: Kubernetes
        - name: ADMIN_ROLE
          value: Primary
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CUSTOM_TEMPORARY_PASSWORD_HASH
          # This field is optional and can only be set for the Primary Admin node.
          # If omitted, no temporary password for the installation API will be set by
          # default, and one can be set using the installation API or Installer UI.
          # Must be a crypt() SHA-512 password hash with format $6$<salt>$<password hash>
          # for a password of at least 8 and no more than 32 characters.
          # This hash can be generated using CLI tools such as the openssl passwd command
          # in SHA-512 mode.
          # Example value: $6$EXAMPLE-SG-abcde$abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
          value: ""
        volumeMounts:
        - mountPath: "/tmp"
          name: tmp
        - mountPath: "/var/local"
          name: var-local
        - mountPath: "/var/local/mysql_ibdata"
          name: mysql
        - mountPath: "/var/local/audit/export"
          name: audit
        - mountPath: "/var/local/nginx/spool"
          name: nginx-spool
        - mountPath: "/var/local/nginx-gw/spool"
          name: nginx-gw-spool
      volumes:
      - name: nginx-spool
        emptyDir:
          medium: Memory
          sizeLimit: 64Mi
      - name: nginx-gw-spool
        emptyDir:
          medium: Memory
          sizeLimit: 64Mi
      - name: tmp
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi
  volumeClaimTemplates:
  - metadata:
      name: var-local
  - metadata:
      name: mysql
  - metadata:
      name: audit
