# Copyright (c) 2019-2020 NetApp, Inc., All Rights Reserved
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-local-dc1-gw-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # Use a storageClass from your cloud provider
  storageClassName: sg-xfs
---
kind: Service
apiVersion: v1
metadata:
  name: dc1-gateway-node
spec:
  type: LoadBalancer
  selector:
    app: dc1-gw-app
  ports:
  - name: s3-gw-https
    port: 8082
    targetPort: 8082
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: dc1-gw
spec:
  serviceName: "pod-dns"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: pod-dns
  template:
    metadata:
      labels:
        app: dc1-gw-app
        name: pod-dns
    spec:
      containers:
      - name: gw-container
        image: storagegrid-11.4.0:API_Gateway
        resources:
          limits:
            cpu: 8
            memory: 24Gi
        securityContext:
          capabilities:
            add: [NET_ADMIN, SYS_ADMIN, SYS_TIME, NET_BIND_SERVICE, SETGID, SETUID, DAC_READ_SEARCH, SYS_RESOURCE, SYSLOG, SYS_PTRACE]
        ports:
        - name: s3-gw-https
          containerPort: 8082
        env:
        - name: SG_CONTAINER_TYPE
          value: Kubernetes
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ADMIN_IP
          value: "dc1-adm-0.pod-dns"
        volumeMounts:
        - mountPath: "/var/local"
          name: var-local
  volumeClaimTemplates:
  - metadata:
      name: var-local
