---
kind: Service
apiVersion: v1
metadata:
  name: pod-dns
  labels:
    name: pod-dns
spec:
  selector:
    name: pod-dns
  clusterIP: None
  ports:
  - name: bogus # Port needed to fake out the service
    port: 12345
    targetPort: 12345
