---
kind: Service
apiVersion: v1
metadata:
  name: admin-node-service
spec:
  type: LoadBalancer
  selector:
    app: adm-app
  ports:
  # This exposes the Admin Node's web interface
  # on a load balanced IP (not really load balancing)
  # This syntax may differ for your K8s service provider
  - name: gmi-https
    protocol: TCP
    port: 443
    targetPort: 443
  # This service is not required for normal operation of the grid
  - name: admin-ssh
    protocol: TCP
    port: 22
    targetPort: 22
---
kind: Service
apiVersion: v1
metadata:
  name: storage-service
spec:
  type: LoadBalancer
  selector:
    app: sn-app
  ports:
  # This exposes the Storage Nodes' S3 interface
  # on a load balanced IP - load-balanced accross all the Storage Nodes
  # This syntax may differ for your K8s service provider
  - name: s3-sn-012-https
    protocol: TCP
    port: 18082
    targetPort: 18082
